### ISSUE TITLE
Import Imagery with Error "raised during agent getStatus"

### ISSUE THREAD

**Issue by freshpomelo** [JaneliaSciComp/jacs-cm#13]
Hi everyone,

Thanks a lot for the issue of https://github.com/JaneliaSciComp/jacs-cm/issues/10#issue-526332269.
Following cgoina's instruction (https://github.com/JaneliaSciComp/jacs-cm/issues/10#issuecomment-565588846), I added the secret key of JACS_API_KEY and JADE_API_KEY in .env.config. The 401 error disappeared.

But there is another error emerged when I tried to import imagery.

I don't know whether I missed some configuration or not.
The error log for jacs-sync is:
```
2019-12-15_01:27:36.445 [XNIO-1 task-26] INFO  o.j.j.r.s.v.d.TmSampleResource [service=] [rootService=] - Creating new TmSample dulab_test with path /jade1/dulab_test
2019-12-15_01:27:36.583 [XNIO-1 task-26] INFO  o.j.j.d.s.DataStorageLocationFactory [service=] [rootService=] - Create JADE volume location with URLs http://SnowMacBook.local:9881/jacsstorage/agent_api/v1, http://SnowMacBook.local:9881/jacsstorage/agent_api/v1/agent_storage/storage_volume/2745716063214768141 and volume path dulab_test
2019-12-15_01:27:36.584 [XNIO-1 task-26] INFO  o.j.j.r.s.v.d.TmSampleResource [service=] [rootService=] - Reading transform.txt from http://SnowMacBook.local:9881/jacsstorage/agent_api/v1/agent_storage/storage_volume/2745716063214768141/dulab_test/
2019-12-15_01:27:36.620 [XNIO-1 task-26] ERROR o.j.j.r.IllegalStateRequestHandler [service=] [rootService=] - Invalid state exception
java.lang.IllegalStateException: java.lang.IllegalStateException: javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused (Connection refused)
	at org.janelia.rendering.JADEBasedDataLocation.openContentStreamFromRelativePathToVolumeRoot(JADEBasedDataLocation.java:123)
	at org.janelia.rendering.JADEBasedDataLocation.getContentFromRelativePath(JADEBasedDataLocation.java:97)
	at org.janelia.jacs2.rest.sync.v2.dataresources.TmSampleResource.getConstants(TmSampleResource.java:421)
	at org.janelia.jacs2.rest.sync.v2.dataresources.TmSampleResource.createTmSample(TmSampleResource.java:251)
	at org.janelia.jacs2.rest.sync.v2.dataresources.TmSampleResource$Proxy$_$$_WeldClientProxy.createTmSample(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:392)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:365)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:318)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:364)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused (Connection refused)
	at org.janelia.rendering.JADEBasedDataLocation.openContentStream(JADEBasedDataLocation.java:164)
	at org.janelia.rendering.JADEBasedDataLocation.openContentStreamFromRelativePathToVolumeRoot(JADEBasedDataLocation.java:120)
	... 58 common frames omitted
Caused by: javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused (Connection refused)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:260)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:254)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:736)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:735)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:395)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:295)
	at org.janelia.rendering.JADEBasedDataLocation.openContentStream(JADEBasedDataLocation.java:152)
	... 59 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:366)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:258)
	... 69 common frames omitted
2019-12-15_01:27:36.622 [XNIO-1 task-26] INFO  o.janelia.jacs2.app.JAXSyncAppConfig [service=] [rootService=] - 172.18.0.15 youmin youmin 'Workstation' PUT http://snowmacbook.local/api/rest-v2/mouselight/data/sample ?subjectKey=user%3Ayoumin status=500 response_bytes=151 rt=0.83 tp=0.007 'Jersey/2.21 (HttpUrlConnection 1.8.0_144)' {"subjectKey":"user:youmin","references":null,"objectIds":null,"ordering":null,"objectType":null,"propertyName":null,"propertyValue":null,"domainObject":{"class":"org.janelia.model.domain.tiledMicroscope.TmSample","name":"dulab_test","ownerKey":null,"readers":[],"writers":[],"creationDate":null,"updatedDate":null,"micronToVoxMatrix":null,"voxToMicronMatrix":null,"origin":null,"scaling":null,"numImageryLevels":null,"files":{"LargeVolumeOctree":"/jade1/dulab_test"},"filesystemSync":true,"filepath":null,"_id":... truncated 
```

And the error log for jade-master is:
```
2019-12-15_01:27:36.510 [XNIO-1 task-432] INFO  o.j.j.rest.MasterStorageResource - Count storage records filtered with: org.janelia.jacsstorage.model.jacsstorage.JacsBundle@5fb5f4fa[entityRefId=JacsBundle#,name=<null>,path=/jade1/dulab_test,storageFormat=<null>,storageVolumeId=<null>,linkedPath=<null>]
2019-12-15_01:27:36.510 [XNIO-1 task-432] INFO  o.j.j.rest.MasterStorageResource - List storage records filtered with: org.janelia.jacsstorage.model.jacsstorage.JacsBundle@5fb5f4fa[entityRefId=JacsBundle#,name=<null>,path=/jade1/dulab_test,storageFormat=<null>,storageVolumeId=<null>,linkedPath=<null>] / org.janelia.jacsstorage.datarequest.PageRequest@12e12b44[firstPageOffset=0,pageNumber=0,pageSize=0,sortCriteria=<null>]
2019-12-15_01:27:36.514 [XNIO-1 task-432] INFO  o.j.j.app.JAXMasterStorageApp - 172.18.0.12 youmin youmin '' GET http://jade-master:8080/jacsstorage/master_api/v1/storage ?storagePath=%2Fjade1%2Fdulab_test&ownerKey=user%3Ayoumin status=200 response_bytes=60 rt=0.016 tp=0.029 'Jersey/2.29.1 (HttpUrlConnection 1.8.0_232)'
2019-12-15_01:27:36.573 [XNIO-1 task-433] INFO  o.j.j.rest.StorageVolumesResource - List storage volumes filtered with: org.janelia.jacsstorage.datarequest.StorageQuery@447cbe35[id=<null>,shared=false,localToAnyAgent=false,dataStoragePath=/jade1/dulab_test,accessibleOnAgent=<null>,storageAgentIds=<null>,storageAgentURLs=<null>,storageName=<null>,storageVirtualPath=<null>,storageTags=[],minAvailableSpaceInBytes=<null>]
2019-12-15_01:27:36.578 [XNIO-1 task-433] INFO  o.j.j.s.d.DistributedStorageVolumeManager - Accessed method: DistributedStorageVolumeManager.findVolumes with {arg0=org.janelia.jacsstorage.datarequest.StorageQuery@447cbe35[id=<null>,shared=false,localToAnyAgent=false,dataStoragePath=/jade1/dulab_test,accessibleOnAgent=<null>,storageAgentIds=<null>,storageAgentURLs=<null>,storageName=<null>,storageVirtualPath=<null>,storageTags=[],minAvailableSpaceInBytes=<null>]}  - 4.56523 ms
2019-12-15_01:27:36.579 [XNIO-1 task-433] INFO  o.j.j.app.JAXMasterStorageApp - 172.18.0.12 youmin youmin '' GET http://jade-master:8080/jacsstorage/master_api/v1/storage_volumes ?dataStoragePath=%2Fjade1%2Fdulab_test&ownerKey=user%3Ayoumin status=200 response_bytes=603 rt=0.011 tp=0.405 'Jersey/2.29.1 (HttpUrlConnection 1.8.0_232)'
2019-12-15_01:27:54.998 [JACS-STORAGE-TASK-0] WARN  o.j.j.s.d.AgentConnectionHelper - Error raised during agent getStatus
javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused (Connection refused)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:260)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:254)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:736)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:735)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:395)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:295)
	at org.janelia.jacsstorage.service.distributedservice.AgentConnectionHelper.getAgentStatus(AgentConnectionHelper.java:31)
	at org.janelia.jacsstorage.service.distributedservice.AgentConnectionTester.testConnection(AgentConnectionTester.java:11)
	at org.janelia.jacsstorage.service.distributedservice.AgentConnectionTester.testConnection(AgentConnectionTester.java:7)
	at org.janelia.jacsstorage.resilience.PeriodicConnectionChecker.lambda$initialize$0(PeriodicConnectionChecker.java:39)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:366)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:258)
	... 20 common frames omitted
2019-12-15_01:28:24.994 [JACS-STORAGE-TASK-0] WARN  o.j.j.s.d.AgentConnectionHelper - Error raised during agent getStatus
javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused (Connection refused)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:260)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:254)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:736)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:735)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:395)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:295)
	at org.janelia.jacsstorage.service.distributedservice.AgentConnectionHelper.getAgentStatus(AgentConnectionHelper.java:31)
	at org.janelia.jacsstorage.service.distributedservice.AgentConnectionTester.testConnection(AgentConnectionTester.java:11)
	at org.janelia.jacsstorage.service.distributedservice.AgentConnectionTester.testConnection(AgentConnectionTester.java:7)
	at org.janelia.jacsstorage.resilience.PeriodicConnectionChecker.lambda$initialize$0(PeriodicConnectionChecker.java:39)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:366)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:258)
	... 20 common frames omitted
2019-12-15_01:28:55.320 [JACS-STORAGE-TASK-0] WARN  o.j.j.s.d.AgentConnectionHelper - Error raised during agent getStatus
javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused (Connection refused)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:260)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:254)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:736)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:735)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:395)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:295)
	at org.janelia.jacsstorage.service.distributedservice.AgentConnectionHelper.getAgentStatus(AgentConnectionHelper.java:31)
	at org.janelia.jacsstorage.service.distributedservice.AgentConnectionTester.testConnection(AgentConnectionTester.java:11)
	at org.janelia.jacsstorage.service.distributedservice.AgentConnectionTester.testConnection(AgentConnectionTester.java:7)
	at org.janelia.jacsstorage.resilience.PeriodicConnectionChecker.lambda$initialize$0(PeriodicConnectionChecker.java:39)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:366)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:258)
	... 20 common frames omitted
2019-12-15_01:29:24.994 [JACS-STORAGE-TASK-0] WARN  o.j.j.s.d.AgentConnectionHelper - Error raised during agent getStatus
javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused (Connection refused)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:260)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:254)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:736)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:735)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:395)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:295)
	at org.janelia.jacsstorage.service.distributedservice.AgentConnectionHelper.getAgentStatus(AgentConnectionHelper.java:31)
	at org.janelia.jacsstorage.service.distributedservice.AgentConnectionTester.testConnection(AgentConnectionTester.java:11)
	at org.janelia.jacsstorage.service.distributedservice.AgentConnectionTester.testConnection(AgentConnectionTester.java:7)
	at org.janelia.jacsstorage.resilience.PeriodicConnectionChecker.lambda$initialize$0(PeriodicConnectionChecker.java:39)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:366)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:258)
	... 20 common frames omitted
```
Any advices would be greatly appreciated.

**Comment by freshpomelo** [comment]
I reconfigured all the settings, the error disappeared, I imported the image successfully.
