### ISSUE TITLE
Import the image

### ISSUE THREAD

**Issue by SupermeLC** [JaneliaSciComp/jacs-cm#7]
Hi,
I have installed the software and login in as the user "root". When I tried to import imagery, it have some error.
I put an image 1.tif (about 120MB) under the path $DATA_DIR/jacsstorage/samples/**test_brain**. In the Workstation, I set "Sample Name" to **test_brain** and "Path to Render Folder" as **/jade1/test_brain**. The error is follow:
```
org.janelia.workstation.core.api.exceptions.RemoteServiceException: Remote service returned InboundJaxrsResponse{context=ClientResponse{method=PUT, uri=https://xxx.xxx.xxx.xxx/SCSW/JACS2SyncServices/v2/mouselight/data/sample?subjectKey=user%3Aroot, status=500, reason=Internal Server Error}} response
	at org.janelia.workstation.core.api.http.RESTClientBase.checkBadResponse(RESTClientBase.java:26)
	at org.janelia.workstation.gui.large_volume_viewer.api.TiledMicroscopeRestClient.create(TiledMicroscopeRestClient.java:137)
	at org.janelia.workstation.gui.large_volume_viewer.api.TiledMicroscopeDomainMgr.save(TiledMicroscopeDomainMgr.java:116)
	at org.janelia.workstation.gui.large_volume_viewer.action.SaveTiledMicroscopeSampleAction$1.doStuff(SaveTiledMicroscopeSampleAction.java:63)
	at org.janelia.workstation.core.workers.SimpleWorker.createResult(SimpleWorker.java:14)
	at org.janelia.workstation.core.workers.SimpleWorker.createResult(SimpleWorker.java:10)
	at org.janelia.workstation.core.workers.ResultWorker.doInBackground(ResultWorker.java:50)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[catch] at java.lang.Thread.run(Unknown Source)
```
How can I solve this problem?
Thanks for your advice！
Liu

**Comment by SupermeLC** [comment]
![image](https://user-images.githubusercontent.com/28586043/66996086-a4e1c980-f102-11e9-9060-c4893851c604.png)

**Comment by krokicki** [comment]
Hi @SupermeLC,

The image data needs to be in a special octree format, and unfortunately, we don't have that documented right now, because most users are generating data at Janelia. 

There is a service in jacs-async which creates the octrees from a stack:
https://github.com/JaneliaSciComp/jacs-compute/blob/master/jacs2-services/src/main/java/org/janelia/jacs2/asyncservice/lvtservices/LVTDataImport.java

The problem is this calls out to some scripts that we have not published yet. We'll do that soon, and I'll update this thread when it's ready. I can't promise that this import method will work for your TIFF, but it will be a good starting point. We'll also add a section to the user manual that describes the data format. 

Thanks for pointing this out to us.

**Comment by SupermeLC** [comment]
Thanks for your reply!

**Comment by krokicki** [comment]
The [user manual](https://github.com/JaneliaSciComp/workstation/blob/master/docs/UserManual.md) now contains a description of the data format on page 100.

**Comment by freshpomelo** [comment]
Hi konrad,
I have a question about the transformation.txt on page 100 of the user manual.
It requires the o{x,y,z} and s{x,y,z} values.
I don't quite understand the definition of o{x,y,z}, which is "the position of the corner of the top-level image in nanometers". What is a "corner"? (Perhaps it is a stupid question. orz)
Why ox,oy,oz} is smaller that sx,sy,sz? I thought sz, sy, sz was the smallest dimension for a image.

Thanks a lot in advance.

**Comment by krokicki** [comment]
I'm not familiar with that part of the code personally, but we do have a service coming out that will generate octrees for you. Stay tuned.

**Comment by cgoina** [comment]
Check https://github.com/JaneliaSciComp/jacs-cm/blob/master/docs/MouseLightDeployment.md under docs. The document now has a section of how to use the service to generate the LVV data. If that is not clear or you have problems running the service please let us know
